
27|const bronzeAppointments=[
28| {id:'onboarding',number:1,title:'Onboarding: Dein Weg zum Kunden-Erfolgssystem',short:'Onboarding und Konzept',duration:'45 min',url:'https://calendly.com/leo-von-pokale-meier/onboarding',description:'Wir legen den Grundstein für dein individuelles Kunden-Erfolgssystem mit Awards: Ausgangslage, Kundenstruktur, Ziele und die Basis deines Award-Konzepts.',agenda:['Anforderungen & Ausblick','Dein Award-Konzept','Dein Start mit der ersten Zielstufe','Nächste Schritte'],fieldDefinitions:[['Ausgangslage & Kundenstruktur','Welche Kunden, Angebote und Ausgangslage bringen wir mit?'],['Ziel des Kunden-Erfolgssystems','Welche Wirkung soll das System für Kunden und Wachstum entfalten?'],['Award-Konzept / Grundidee','Anlass, Zielgruppe, Botschaft und erster Ansatz'],['Erste Zielstufe','Name, Kriterien und Startpunkt'],['Nächste Schritte','Entscheidungen, Aufgaben, Verantwortliche und Termin'] ]},
29| {id:'daten-checkup',number:2,title:'Daten-Checkup: Deine erste Award-Stufe',short:'Daten-Checkup',duration:'30 min',url:'https://calendly.com/leo-von-pokale-meier/daten-checkup',description:'Wir übersetzen dein Award-Konzept in konkrete Inhalte, Designgrundlagen und Umsetzungsdaten für die erste Award-Stufe.',agenda:['Titel und Bedeutung der ersten Award-Stufe','Gestaltungs- und CI-Elemente','Texte, Kundennamen und Lieferadressen','Fehlende Daten und Entscheidungen'],fieldDefinitions:[['Titel der ersten Award-Stufe',''],['Bedeutung & Wirkung für Kunden','Fortschritt, Status, Leistung, Transformation oder Zugehörigkeit'],['Marke / Gestaltung / CI','Farben, Bildwelt, Logo, Gestaltungs-Elemente'],['Inhalte & Texte','Auszeichnungstext, Namen, Daten'],['Kundennamen & Lieferadressen',''],['Offene Daten / Entscheidungen',''] ]},
30| {id:'follow-up',number:3,title:'Follow Up: Deine ersten Übergaben im Erfolgs-System',short:'Follow Up',duration:'20 min',url:'https://calendly.com/leo-von-pokale-meier/follow-up-start',description:'Design, Konzept und die ersten Awards sind ausgeliefert. Jetzt planen wir die ersten Übergaben so, dass sie maximale Strahlkraft für dich und deine Kunden entfalten.',agenda:['Ankündigung & maximaler Nutzen','Praxis-Tipps für die Übergabe','Timing & Ablauf','Wirkung nach der Übergabe','Konkreter Maßnahmenplan'],fieldDefinitions:[['Geplante Übergaben','Wem, wann und bei welchem Anlass?'],['Ankündigung & Nutzenversprechen','Wie wird der Moment vorbereitet und angekündigt?'],['Ablauf, Worte & Setting','Persönlich, digital begleitet, Kundentermin oder Event?'],['Wirkung danach','Feedback, Foto, Reaktion, Social Proof, Testimonial'],['Maßnahmenplan','Vorbereitung, Verantwortliche, nächster Checkpoint'] ]},
31| {id:'strategie',number:4,title:'Strategietermin: Die Stufen deines Erfolgs-Systems',short:'Strategietermin',duration:'45 min',url:'https://calendly.com/leo-von-pokale-meier/beratungstermin-bronze-stufensystem',description:'Wir werten die ersten Übergaben aus und entwickeln dein vollständiges Stufensystem mit drei Award-Stufen, klaren Touchpoints, Handlungen und Conversion-Zielen.',agenda:['Auswertung der ersten Übergaben','Review der bisherigen Umsetzung','Aufbau des Stufensystems','Nächste Schritte und Silber-Phase'],fieldDefinitions:[['Erkenntnisse aus den Übergaben','Reaktionen, Feedback, Fotos, offene Fragen'],['Was hat funktioniert / was wird besser?',''],['Stufensystem','3 Award-Stufen, Meilensteine, Touchpoints und Ziele'],['Handlungen & Conversion-Ziele',''],['Nächste Schritte / Silber-Phase','Entscheidung, Aufgaben und Termin'] ]}
32|];
33|const silverAppointments=[['Trust-Building','Hacks für mehr Vertrauen deiner Kunden in deine Versprechen'],['Sichtbarkeit & Brand','Maßnahmen für maximale Sichtbarkeit deiner Kundenerfolge'],['Messbarkeit','KPIs und Zielstufen werden messbar und transparent'],['Empfehlungsprozess & Anreizsystem','Bonus: analoges Anreizsystem auf der Rückseite deiner Frames']];
34|const defaultState={appointmentNotes:{},client:{company:'',contact:''},customers:[],awards:[],referrals:[],agreements:[]};
35|// Kompatible Renderer für die Gen-1-Register; die Datensätze werden weiterhin lokal gehalten.
36|function renderCustomers(){return state.customers||[]} function renderAwards(){return state.awards||[]} function renderReferrals(){return state.referrals||[]} function renderAgreements(){return state.agreements||[]}
37|let state;try{state=JSON.parse(localStorage.getItem('pm-erfolgsportal-gen2'))||defaultState}catch{state=defaultState}state.appointmentNotes||={};state.client||={company:'',contact:''};
38|const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const save=()=>localStorage.setItem('pm-erfolgsportal-gen2',JSON.stringify(state));
39|const noteFor=id=>state.appointmentNotes[id]||{status:'open',fields:{},bookingNote:''};const doneCount=()=>bronzeAppointments.filter(a=>noteFor(a.id).status==='done').length;const isBronzeComplete=()=>doneCount()===bronzeAppointments.length;const unlockIndex=()=>bronzeAppointments.findIndex(a=>noteFor(a.id).status!=='done');
40|function statusText(a,index){const n=noteFor(a.id);if(n.status==='done')return 'erledigt';if(index===unlockIndex())return n.status==='booked'?'gebucht':'bereit';return 'gesperrt'}
41|function renderPhases(){const bronze=doneCount(), complete=isBronzeComplete();const cards=[`<article class="card phase-card"><div class="eyebrow" style="color:var(--gold)">Phase 1</div><h3>Bronze</h3><p>Onboarding, erste Award-Stufe, Übergaben und dein vollständiges Stufensystem.</p><div class="progress"><i style="width:${bronze/4*100}%"></i></div><div class="phase-footer"><span>${bronze} von 4 Terminen erledigt</span><span class="badge">aktiv</span></div></article>`,`<article class="card phase-card silver ${complete?'':'locked'}"><div class="eyebrow" style="color:${complete?'var(--silver)':'inherit'}">Phase 2</div><h3>Silber</h3><p>Vertrauen, Sichtbarkeit, Messbarkeit und Empfehlungen.</p><div class="progress"><i style="width:${complete?8:0}%"></i></div><div class="phase-footer"><span>${complete?'bereit für den Start':'Bronze komplett abschließen'}</span><span class="badge">${complete?'freigeschaltet':'gesperrt'}</span></div></article>`,`<article class="card phase-card locked"><div class="eyebrow">Phase 3</div><h3>Leuchtfeuer</h3><p>Die nächste Ausbaustufe wird später ergänzt.</p><div class="phase-footer"><span>noch in Konzeption</span><span class="badge">später</span></div></article>`];$(\'#phase-overview\').innerHTML=cards.join('');$(\'#phase-visualization\').innerHTML=cards.join('');$(\'#phase-library\').innerHTML=cards.join('')+`<article class="card ${complete?'':'locked'}"><div class="eyebrow" style="color:var(--silver)">Silber-Highlights</div><h3>${complete?'Silber kann starten':'Silber ist ausgegraut'}</h3><div class="silver-list">${silverAppointments.map(x=>`<div class="silver-item"><b>${esc(x[0])}</b><small>${esc(x[1])}</small></div>`).join('')}</div>${complete?'<button class="button" type="button">Silber starten</button>':''}</article>`}
42|function appointmentCard(a,index){const n=noteFor(a.id), status=statusText(a,index), unlocked=index===unlockIndex()||n.status==='done';const action=n.status==='done'?`<button class="button secondary" data-doc="${a.id}">Termin-Dokument öffnen</button>`:unlocked?`<button class="button" data-book="${a.id}">Nächsten Termin buchen</button><button class="button secondary" data-doc="${a.id}">Termin-Dokument</button>`:`<button class="button secondary" disabled>Termin freischalten</button>`;return `<article class="appointment-card ${status==='gesperrt'?'locked':''} ${n.status==='done'?'done':''}"><div class="number">${a.number}</div><div><div class="meta"><span>Bronze</span><span>·</span><span>${a.duration}</span><span class="badge">${status}</span></div><h3>${esc(a.title)}</h3><p>${esc(a.description)}</p></div><div class="action-group">${action}</div>${unlocked?documentPane(a,n):''}</article>`}
43|function documentPane(a,n){return `<div class="doc-header" style="grid-column:2/-1"><div class="eyebrow" style="color:var(--green)">Termin-Dokument</div><h2>${esc(a.short)}</h2><p class="muted">Die Felder sind bewusst als erste freie Version angelegt. Die spätere Zuordnung zu Zoho optimieren wir separat.</p><div class="agenda"><h3>Das erwartet dich</h3><p>${esc(a.description)}</p><ol>${a.agenda.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div><div class="form-grid">${a.fieldDefinitions.map(([label,hint],i)=>`<div class="field ${i===a.fieldDefinitions.length-1?'full':''}"><label>${esc(label)}<textarea data-field="${a.id}:${i}" placeholder="${esc(hint)}">${esc(n.fields?.[i]||'')}</textarea></label></div>`).join('')}</div><div class="field full" style="margin-top:13px"><label>Interne Notizen / Ergebnis<textarea data-field="${a.id}:internal" placeholder="Wichtige Aussagen, Entscheidungen und Follow-ups">${esc(n.fields?.internal||'')}</textarea></label></div><div class="save-row"><button class="button secondary" data-save-note="${a.id}">Notizen speichern</button>${n.status!=='done'?`<button class="button" data-done="${a.id}">Termin erledigen</button>`:''}<span id="saved-${a.id}" class="saved"></span></div>${a.id==='strategie'?`<div class="bonus"><b>BONUS nach Bronze:</b> 3 Sample-Awards, jeweils ein Award pro Stufe. Sie können direkt für dein eigenes Marketing genutzt werden.</div>`:''}</div>`}
44|function renderAppointments(){$('#appointment-list').innerHTML=bronzeAppointments.map(appointmentCard).join('');document.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>openBooking(b.dataset.book));document.querySelectorAll('[data-doc]').forEach(b=>{b.onclick=()=>{const card=b.closest('.appointment-card');const doc=card.querySelector('.doc-header');if(doc)doc.scrollIntoView({behavior:'smooth',block:'start'})}});document.querySelectorAll('[data-save-note]').forEach(b=>b.onclick=()=>saveNotes(b.dataset.saveNote));document.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>finishAppointment(b.dataset.done));}
45|function renderOverview(){const next=bronzeAppointments[unlockIndex()];$('#bronze-progress-number').textContent=`${doneCount()} / 4`;$('#next-title').textContent=next?next.short:'Bronze komplett';$('#next-detail').textContent=next?(noteFor(next.id).status==='booked'?'Gebucht – Dokument ausfüllen und danach erledigen':'Bereit zur Buchung'):'3 Samples sind freigegeben';$('#silver-status').textContent=isBronzeComplete()?'bereit':'gesperrt'}
46|function render(){renderPhases();renderAppointments();renderOverview();save()}
47|function saveNotes(id){const a=bronzeAppointments.find(x=>x.id===id),n=noteFor(id);n.fields={};a.fieldDefinitions.forEach((_,i)=>n.fields[i]=$(`[data-field="${id}:${i}"]`)?.value.trim()||'');n.fields.internal=$(`[data-field="${id}:internal"]`)?.value.trim()||'';state.appointmentNotes[id]=n;save();$(`#saved-${id}`).textContent='Gespeichert';setTimeout(()=>{$(`#saved-${id}`) && ($(`#saved-${id}`).textContent='')},1800)}
48|function finishAppointment(id){saveNotes(id);state.appointmentNotes[id].status='done';save();render()}
49|let bookingId='';function openBooking(id){bookingId=id;const a=bronzeAppointments.find(x=>x.id===id);$('#booking-title').textContent=`${a.short} buchen`;$('#booking-note').value=noteFor(id).bookingNote||'';$('#booking-dialog').showModal()}
50|$('#booking-form').onsubmit=e=>{e.preventDefault();const a=bronzeAppointments.find(x=>x.id===bookingId),n=noteFor(bookingId);n.status='booked';n.bookingNote=$('#booking-note').value.trim();state.appointmentNotes[bookingId]=n;save();$('#booking-dialog').close();window.open(a.url,'_blank','noopener');render()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
51|$('#client-company').value=state.client.company||'';$('#client-contact').value=state.client.contact||'';$('#save-client').onclick=()=>{state.client={company:$('#client-company').value.trim(),contact:$('#client-contact').value.trim()};save();$('#client-saved').textContent='Gespeichert';setTimeout(()=>$('#client-saved').textContent='',1800)};
52|document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.view}`).classList.add('active')});render();
53|